### ISSUE TITLE
Opem MPI programs not releasing memory during run

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#1163] opened 2024-08-23 14:56 UTC
The ompi programs do not release memory and cause the insufficient memory error. 
_forrtl: severe (41): insufficient virtual memory_

[test-err.zip](https://github.com/user-attachments/files/16730406/test-err.zip)

y-axis free memory, x-axis time in minute
![image](https://github.com/user-attachments/assets/42d65043-7cc6-497c-81cc-091939b4338f)
Vertical line indicates crash of program

**Comment by DavidSagan** [comment] 2024-08-24 09:32
@henrylovelace3 I am not able to reproduce this. And I tried both ifort (17.0.7) and gfortran (11.2.1) Can you try running on a different machine to see what happens?

**Comment by henrylovelace3** [comment] 2024-08-24 15:59
@DavidSagan 
Attached is a script that if you are using linux will produce the data used in the file. I have tried this on a different machine with the same result. To run the script:
bash mem_log.txt
[log-mem.txt](https://github.com/user-attachments/files/16737225/log-mem.txt)

If you run the script in concert with the mpi programs, you will see that the free memory will slowly deplete.

**Comment by DavidSagan** [comment] 2024-08-25 00:55
@henrylovelace3 This does not look like a script.

**Comment by henrylovelace3** [comment] 2024-08-25 09:47
You are right, it was an output. Sorry about that. Attached is the script
[mem_log.txt](https://github.com/user-attachments/files/16739661/mem_log.txt)

**Comment by DavidSagan** [comment] 2024-08-26 20:35
@henrylovelace3 It is not a question of monitoring the memory usage. When I run with your input files I do not see the memory used going up.

**Comment by DavidSagan** [comment] 2024-10-16 02:08
Since I cannot reproduce this I am closing the ticket.

**Closed as completed by DavidSagan** 2024-10-16 02:08 UTC
